name: Build and push docker images

on:
  push:
    branches:    
      - master

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-18.04
    steps:
    - name: Check out code
      uses: actions/checkout@v2.3.2

    - name: Build & push docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: alvisisme/dotnet
        tags: 6.0
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
